# Generated by Django 5.0.1 on 2024-01-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_form_murojat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Murojat',
        ),
        migrations.AddField(
            model_name='form',
            name='phone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
